#!/usr/bin/env python3
"""wiki_reindex.py — regenerate agent_wiki/index.md and lint page frontmatter.

Usage:
    python3 scripts/wiki_reindex.py agent_wiki              # lint + rewrite index
    python3 scripts/wiki_reindex.py agent_wiki --lint-only  # lint only, no write
    python3 scripts/wiki_reindex.py agent_wiki --check      # lint + index must be current

Standard library only, on purpose. Some origin-project equivalents depend on PyYAML;
this repository's gates run on a bare CI runner, so a dependency here would make
the wiki gate unrunnable in exactly the environment that is supposed to prove it.
The frontmatter schema is kept compatible across our repositories so pages can
move between them unchanged.

Layers (see agent_wiki/AGENTS.md):
- `agent_wiki/*.md`     durable engineering knowledge — indexed and linted here
- `agent_wiki/runtime/` runtime/work handoffs — deliberately NOT indexed; it is
                        working state, reached through the `.omc/wiki`
                        compatibility entry from Claude and by plain file
                        operations from Codex

Exit codes: 0 clean (warnings allowed), 1 lint error or stale index, 2 usage.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Compatible with the shared agent_wiki schema used across our repositories.
REQUIRED_FIELDS = ("category", "tags", "sources", "confidence")
CONFIDENCE_VALUES = ("high", "medium", "low")

# `session-log` is deliberately absent: the typed-knowledge contract forbids
# session transcripts in a durable store, and this repository has round reports
# for anything time-ordered.
CATEGORY_ORDER = (
    "architecture",
    "decision",
    "pattern",
    "debugging",
    "convention",
    "reference",
    "environment",
)

SKIP_FILES = {"index.md", "log.md", "AGENTS.md", "README.md"}

INDEX_HEADER = """# Wiki Index

> {count} durable page{plural}
> Auto-generated by `scripts/wiki_reindex.py`. Do not hand-edit; rerun after changes.
> Runtime/work pages under `runtime/` are working state and are not indexed here.
"""


def split_frontmatter(text: str):
    """Return (frontmatter_text, body) or (None, text) when there is no block."""
    if not text.startswith("---"):
        return None, text
    end = text.find("\n---", 3)
    if end == -1:
        return None, text
    return text[3:end], text[end + 4 :]


def parse_frontmatter(raw: str) -> dict:
    """Minimal YAML subset: scalars, inline [a, b] lists, and block `- item` lists.

    Enough for this schema and nothing more — a real YAML parser is not worth a
    dependency here, and anything this cannot express does not belong in a wiki
    header.
    """
    data: dict = {}
    key = None
    for line in raw.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line.startswith((" ", "\t")) and line.lstrip().startswith("- "):
            if key is not None:
                data.setdefault(key, [])
                if isinstance(data[key], list):
                    data[key].append(unquote(line.lstrip()[2:].strip()))
            continue
        match = re.match(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$", line)
        if not match:
            continue
        key, value = match.group(1), match.group(2).strip()
        if value == "":
            data[key] = []
        elif value.startswith("[") and value.endswith("]"):
            inner = value[1:-1].strip()
            data[key] = [unquote(p.strip()) for p in inner.split(",") if p.strip()]
        else:
            data[key] = unquote(value)
    return data


def unquote(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def page_title(meta: dict, body: str, path: Path) -> str:
    title = meta.get("title")
    if isinstance(title, str) and title.strip():
        return title.strip()
    for line in body.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem


def page_summary(body: str) -> str:
    """First real prose line after the H1, truncated — index entries are pointers."""
    seen_heading = False
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            seen_heading = True
            continue
        if not seen_heading:
            continue
        if stripped.startswith(("```", ">", "|", "-", "*")):
            continue
        return stripped[:160]
    return ""


def lint_page(path: Path, meta: dict | None, body: str) -> list[str]:
    rel = path.relative_to(ROOT)
    if meta is None:
        return [f"{rel}: missing frontmatter block"]

    errors = []
    for field in REQUIRED_FIELDS:
        if field not in meta:
            errors.append(f"{rel}: missing required frontmatter field '{field}'")

    category = meta.get("category")
    if isinstance(category, str) and category and category not in CATEGORY_ORDER:
        if category == "session-log":
            errors.append(
                f"{rel}: category 'session-log' is not allowed in the durable "
                f"store — session transcripts belong in a round report"
            )
        else:
            errors.append(
                f"{rel}: unknown category '{category}' "
                f"(allowed: {', '.join(CATEGORY_ORDER)})"
            )

    confidence = meta.get("confidence")
    if isinstance(confidence, str) and confidence and confidence not in CONFIDENCE_VALUES:
        errors.append(
            f"{rel}: confidence '{confidence}' "
            f"(allowed: {', '.join(CONFIDENCE_VALUES)})"
        )

    for field in ("tags", "sources"):
        if field in meta and not isinstance(meta[field], list):
            errors.append(f"{rel}: '{field}' must be a list")

    if isinstance(meta.get("tags"), list) and not meta["tags"]:
        errors.append(f"{rel}: 'tags' is empty — a page nobody can find is not knowledge")

    if not body.strip():
        errors.append(f"{rel}: page body is empty")

    return errors


def build_index(pages: list[tuple[str, str, str, str]]) -> str:
    """pages: (category, title, filename, summary), already collected."""
    count = len(pages)
    out = [INDEX_HEADER.format(count=count, plural="" if count == 1 else "s")]

    by_category: dict[str, list[tuple[str, str, str]]] = {}
    for category, title, filename, summary in pages:
        by_category.setdefault(category, []).append((title, filename, summary))

    known = [c for c in CATEGORY_ORDER if c in by_category]
    unknown = sorted(c for c in by_category if c not in CATEGORY_ORDER)
    for category in known + unknown:
        out.append(f"\n## {category}\n")
        for title, filename, summary in sorted(by_category[category]):
            suffix = f" — {summary}" if summary else ""
            out.append(f"- [{title}]({filename}){suffix}")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("store", nargs="?", default="agent_wiki")
    parser.add_argument("--lint-only", action="store_true", help="lint, never write")
    parser.add_argument(
        "--check",
        action="store_true",
        help="lint and fail if index.md is not what would be generated",
    )
    args = parser.parse_args()

    store = ROOT / args.store
    if not store.is_dir():
        print(f"ERROR: no such wiki store: {args.store}", file=sys.stderr)
        return 2

    errors: list[str] = []
    pages: list[tuple[str, str, str, str]] = []

    for path in sorted(store.glob("*.md")):
        if path.name in SKIP_FILES:
            continue
        text = path.read_text(encoding="utf-8")
        raw, body = split_frontmatter(text)
        meta = parse_frontmatter(raw) if raw is not None else None
        page_errors = lint_page(path, meta, body)
        errors.extend(page_errors)
        if meta is None:
            continue
        category = meta.get("category") or "reference"
        if not isinstance(category, str):
            category = "reference"
        pages.append(
            (category, page_title(meta, body, path), path.name, page_summary(body))
        )

    index_text = build_index(pages)
    index_path = store / "index.md"
    current = index_path.read_text(encoding="utf-8") if index_path.exists() else None

    runtime_dir = store / "runtime"
    runtime_count = (
        len([p for p in runtime_dir.glob("*.md") if p.name not in SKIP_FILES])
        if runtime_dir.is_dir()
        else 0
    )

    if errors:
        for error in errors:
            print(f"WIKI LINT: {error}", file=sys.stderr)
        print(f"Wiki lint failed: {len(errors)} issue(s) in {args.store}", file=sys.stderr)
        return 1

    if args.check:
        if current != index_text:
            print(
                f"ERROR: {args.store}/index.md is stale — "
                f"run `python3 scripts/wiki_reindex.py {args.store}`",
                file=sys.stderr,
            )
            return 1
        print(
            f"Wiki OK: {len(pages)} durable page(s) indexed, "
            f"{runtime_count} runtime page(s) not indexed, index current"
        )
        return 0

    if args.lint_only:
        print(f"Wiki lint passed: {len(pages)} durable page(s) in {args.store}")
        return 0

    if current != index_text:
        index_path.write_text(index_text, encoding="utf-8")
        print(f"Wrote {args.store}/index.md ({len(pages)} page(s))")
    else:
        print(f"{args.store}/index.md already current ({len(pages)} page(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
